{% set name = "speg" %}
{% set version = "0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/speg-{{ version }}.zip
  sha256: 10cbef47e168dfc62f14db575cf1c428037a2b881cee6c3cfceda0439c243e71

build:
  number: 1001
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - speg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avakar/speg
  summary: A PEG-based parser interpreter with memoization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dfroger
