{% set name = "speg" %}
{% set version = "0.2" %}
{% set sha256 = "474b083021379a4e6aa1465879eeaeab3f70cbf474d52f9845f0872741aa3635" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - speg

about:
  home: https://github.com/avakar/speg
  license: MIT
  license_family: MIT
  summary: 'A PEG-based parser interpreter with memoization.'

extra:
  recipe-maintainers:
    - dfroger
