travis:
  secure:
    BINSTAR_TOKEN: MUG/iYJc8PA5qgv5Yb5zHcn0WIuC2HnxfRMbRMenadN8XUasvjibnm46+plHX5U/djli5oENSUZ0Ar1xmh4qbl8MtrIVJQu6hlDrHcia5DXPaAdN6or3V1co1tTvg/fR+UkcTBL3ACYzIuj83o5gWUX3KcXsY3BSVZbwWdYUy3wRjIjQhPPciIDQc/GL8O+riFIr2Ic+ka8B5pmjcniTPCuHmQGJiMrdxeDGz5kuZiY/l1qHQV5zfF+zMH84qgX3nFsv+7Qj79veyaBerAtKjSdqpl7yH4oCUnKxd/a9SsrDAy7MZoeP4b/o8kTnepEytMXk/RvYlPygAJ4Ka1HbQNZKyokJEQXel62ODE63XtkqkHdsg6d8yUyG6y/zklCi+d/5kPMihOGrRb6AMNFXUAhqZu1woMgM8wCszfRK/oMkgvuFxIeOzGSN1Bnsw5GSaPWTuP+b88yUMyLGZXSrQHaRdH7l0fQHz/Mz7ytRIlHc2sVrAOD6U7B5JElkRNzyzm4a0O6SMNTCZNOZq1ZSX6pDZuBrSMPvM+tsAAUaLv4rVCvtkgNGQJGA/qeNbiw61AM6nt3aFNLnCGP1+2RlTJZPz6H8VJBCzzb9B+urd5NLq+bO6hKJ3z+s67kB61oOFf1sVUnux76fmue3E0rtzJvhbaRmvMOmLBqL2LBaias=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
