appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ETYQiEC1dyNFr4CZ6sBSveAOaCuVC6/hMtteLz17eaha3FZj456n8QwoqtmtsBPvqgXYE3VW3GU7jJZ1E/LDqCIfclK8uMSfO4knEPqdDohvl5+AEMxzMwka5xj2qTzf7Afb/5L/GayRRGmLc6yz65AzSbEKbtZ+TdocUxmCbJTpRQxorGca7cDO+GsaySeafsBB8CB9vXiil2VpZ5+o/dyZtPxzJsYEmDZ3VGrbPa+ZUneR3jikwn7VBmpKO7AUNjKz3y8BR+N9aPBbTA5xtHuxNbTQFOBLJFlNkI1N0po9zNJ5w5kbxBwUWSmwxWLrfUPbCCQKRvAIVoKs1UsQIQ2s8sztSq+8k5/xM2o2m/fh2azG8H2QXy+RZ2TsWFG5YG9p09kSZ5bgCfLB+s0ILMX8ByiIsJbcy2cEBnwvFjSjoDJCyfCr0OHz3G1iEVV52YcViZvJR4yhTkUuwW3QfVBvECju0fDIGOoPC/Y85tun3mbwhc4xAhs/hAQrCEC6/feuXNrMnGwyEkezFqab4upEIUEIeT2otguU7ZnV/Zh0/7/roEco4ILy8oSXj0tReHYpPMNSsZ9B+Fj1bODo8WgrE7KMs0/Eb9KQfZnzDylZ0981PcU4DY+TDb3NCXv3qoRT7Be7Y9czUWgX7MyeZNWMRfjdn+F5iMFGuXha3cg=}
conda_forge_output_validation: true
