travis:
  secure:
    BINSTAR_TOKEN: pmBSt7vNJicYEO3+UZ4AE1ktBvFnKbikv6Zmn1ItcIdG6lGKZy9vcw9WeWnougfLOzQCCXeZxTRjVf2W6jstAQe+3RcOiCV7Scsurus3n7zQ2OwtzDSZQBlboiJCiIpFRnrAueo7q7iM5jKYxk1EeWiZDkzIPbYcJGCwj8QTE6cCeTIu73xLN/NHKQhcfCbMgxVW+37jb6SvvTMfcRVYdLJfrB0jptrw342egUX3tH5WVm1uoVuCyxbs45z3tRXzkD+DuJ2OCRR22CbdLcfKgX6e4CF0I6jrHN2pNg9GU70NJwME/5QHjUJx+ZaE8Ngq3CERqr+tkJdCtJxrUhDZT9bpKejKQ3iqhwLYbvQ36bS1/EtjoXv8nqcMDMPOB3R5ZSoQ82yZ6txpOvjzCoe2BsHWfUljMhRoZACoDh7cHktw18Dv9Nv8sf+IWX5geVKeAj2MnL5G0isSgu4Mp8HQ5dxv+7bQLojtqzyGFYs/gVLV2a64mPXkZh+ptvsRVSuKUqjVWOT2CHpK1gbh9tOWuj5x8DYrSoAwSrdbyyXru6vuIC25pC6dVoDlOVSIp06HMY8JqcSPxq/Y4RyhJX7TDH703hj3Ymh+JydHulvzQ1qGSgpQgesIkLKWgxyeFFPV+WGNHiNeYRUJycbqbvuZ0SR5QoIncyfQNBS0mPoTRHI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
